window.SAMPLE_MESSAGES = [
  {"msg_id": "M21817", "channel": "announcement", "author_role": "btc", "created_at_vn": "2026-09-13 08:42", "content": "🚀 THÔNG BÁO WORKSHOP 02 — vào tối 13/9 (hôm nay) chúng ta sẽ đi vào Buổi WS 2 với chủ đề: Problem → MVP Canvas. Thời gian: 20:00 — tối nay, ngày 13/09; Hình thức: Online qua Zoom.", "note": "Channel gán minh hoạ cho demo — dữ liệu gốc ẩn danh, không có tên kênh thật (xem DATA_DICTIONARY.md)."},
  {"msg_id": "M09449", "channel": "announcement", "author_role": "btc", "created_at_vn": "2026-09-13 21:49", "content": "📢 THÔNG BÁO LỰA CHỌN ĐỀ TÀI — Các mốc thời gian quan trọng: 22:00 Chủ [HV] 13/09/2026: Công khai ngân hàng đề tài; 23:59 Chủ [HV] 20/09/2026: Hạn cuối lựa chọn và đăng ký đề tài.", "note": "Channel gán minh hoạ cho demo — dữ liệu gốc ẩn danh, không có tên kênh thật."},
  {"msg_id": "SYN-08", "channel": "thong-bao-lop", "author_role": "coach", "created_at_vn": "2026-09-16 17:45", "content": "Các nhóm cụm 1-3 di chuyển hết sang phòng E403 để họp chung với Coach nhé!", "note": "Synthetic — tái sử dụng nguyên văn quote đã duyệt ở CP2 (Card 2 trong prototype)."},
  {"msg_id": "SYN-03", "channel": "general", "author_role": "hoc_vien", "created_at_vn": "2026-09-16 18:15", "content": "nhóm nào chưa có willing user thì tìm sớm đi nhé, lát nộp CP1 phải khai tên rồi đấy", "note": "Synthetic — tái sử dụng nguyên văn quote đã duyệt ở CP2 (Card 3 trong prototype)."},
  {"msg_id": "M72484", "channel": "general", "author_role": "hoc_vien", "created_at_vn": "2026-09-12 23:53", "content": "Hạn nộp Lab02", "note": "Channel gán minh hoạ cho demo — dữ liệu gốc ẩn danh, không có tên kênh thật."},
  {"msg_id": "SYN-06", "channel": "lab-qa", "author_role": "hoc_vien", "created_at_vn": "2026-09-13 14:00", "content": "lỗi import pandas fix sao ạ", "note": "Synthetic — câu hỏi kỹ thuật thuần tuý để test lọc ngoài phạm vi."},
  {"msg_id": "SYN-19", "channel": "random", "author_role": "hoc_vien", "created_at_vn": "2026-09-13 22:00", "content": "@everyone Cảm ơn cả nhà đã tham gia workshop hôm nay rất nhiệt tình ạ 🎉", "note": "Synthetic — tán gẫu để test không bịa card từ tag @everyone."}
]
;